# fly.toml app configuration file generated for avinash on 2023-05-08T12:21:31+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "avinash"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
